defaultPortal: cuenta-de-prueba-de-desarrollador-1
portals:
  - name: cuenta-de-prueba-de-desarrollador-1
    portalId: 47769808
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMHAwKqsMhIRAA0AQAAA4G0DQAJYAgEAAPgY0NHjFiCv4u8hKO7pDDIUbv5hmt6SUqMryZJ3I0sUe8Wcq6w6TAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DAAAAAAAAAAwEAAAAAAAAAAAAABBCFIRHirHJ0drBIpr7exZt4VNA3WdBSgNuYTFSAFoAYAA
        expiresAt: '2024-10-25T20:13:35.721Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRuYTEtNjg0ZC0yNzYyLTQzOTgtYTg4NC1lZjU0Y2I0OTQ5NDAQ0NHjFhiv4u8hKhkABeaRguheLhVaPt2hclKk_KbpahT5JdfHSgNuYTE
    parentAccountId: 47763893
